#!/usr/bin/env python3
"""Generate CATALOG.md and README category counts from SKILL.md frontmatter."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "CATALOG.md"
README = ROOT / "README.md"
SKIP_DIRS = {".git", ".github", "node_modules"}
TABLE_START = "<!-- BEGIN GENERATED CATEGORY TABLE -->"
TABLE_END = "<!-- END GENERATED CATEGORY TABLE -->"


@dataclass(frozen=True)
class Skill:
    category: str
    path: Path
    name: str
    description: str


ABBREVIATIONS = {"e.g", "i.e", "etc", "v", "vs", "mr", "mrs", "ms", "dr"}


def shorten(text: str, limit: int = 220) -> str:
    text = re.sub(r"\s+", " ", text).strip()
    if len(text) <= limit:
        return text

    for match in re.finditer(r"[.!?](?:\s|$)", text[:limit]):
        token = text[: match.start()].rsplit(" ", 1)[-1].lower().rstrip(".")
        if token not in ABBREVIATIONS:
            return text[: match.start() + 1]

    cut = text[: limit - 1].rsplit(" ", 1)[0]
    return f"{cut}…"


def parse_simple_frontmatter(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{path.relative_to(ROOT)} is missing YAML frontmatter")

    end = text.find("\n---", 4)
    if end == -1:
        raise ValueError(f"{path.relative_to(ROOT)} has unterminated YAML frontmatter")

    frontmatter = text[4:end].splitlines()
    data: dict[str, str] = {}
    i = 0
    while i < len(frontmatter):
        line = frontmatter[i]
        if not line.strip() or line.lstrip().startswith("#") or ":" not in line:
            i += 1
            continue
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        if value in {"|", ">", "|-", ">-"}:
            block: list[str] = []
            i += 1
            while i < len(frontmatter) and (frontmatter[i].startswith(" ") or not frontmatter[i].strip()):
                block.append(frontmatter[i].strip())
                i += 1
            data[key] = " ".join(block).strip()
            continue
        data[key] = value.strip('"\'')
        i += 1
    return data


def parse_frontmatter(path: Path) -> tuple[str, str]:
    data = parse_simple_frontmatter(path)
    missing = [key for key in ("name", "description") if not data.get(key)]
    if missing:
        fields = ", ".join(missing)
        raise ValueError(f"{path.relative_to(ROOT)} is missing required frontmatter: {fields}")
    return data["name"], data["description"]


def load_category_descriptions() -> dict[str, str]:
    descriptions: dict[str, str] = {}
    for path in sorted(ROOT.glob("*/DESCRIPTION.md")):
        rel = path.relative_to(ROOT)
        if any(part in SKIP_DIRS or part.startswith(".") for part in rel.parts):
            continue
        data = parse_simple_frontmatter(path)
        descriptions[path.parent.name] = data.get("description", "")
    return descriptions


def iter_skills() -> list[Skill]:
    skills: list[Skill] = []
    for path in ROOT.glob("**/SKILL.md"):
        rel = path.relative_to(ROOT)
        if any(part in SKIP_DIRS or part.startswith(".") for part in rel.parts):
            continue
        category = rel.parts[0]
        name, description = parse_frontmatter(path)
        skills.append(Skill(category, path, name, description))
    return sorted(skills, key=lambda s: (s.category, str(s.path)))


def markdown_table_row(values: list[str]) -> str:
    escaped = [value.replace("|", "\\|").replace("\n", " ") for value in values]
    return "| " + " | ".join(escaped) + " |"


def group_by_category(skills: list[Skill]) -> dict[str, list[Skill]]:
    by_category: dict[str, list[Skill]] = {}
    for skill in skills:
        by_category.setdefault(skill.category, []).append(skill)
    return by_category


def build_category_table(
    by_category: dict[str, list[Skill]],
    descriptions: dict[str, str],
    link_prefix: str,
    link_suffix: str = "",
) -> list[str]:
    lines = [
        "| Category | Skills | Description |",
        "|---|---:|---|",
    ]
    for category in sorted(by_category):
        description = descriptions.get(category, "")
        link = f"{link_prefix}{category}{link_suffix}"
        lines.append(markdown_table_row([f"[{category}]({link})", str(len(by_category[category])), description]))
    return lines


def build_catalog(skills: list[Skill], descriptions: dict[str, str]) -> str:
    by_category = group_by_category(skills)

    lines = [
        "# Skills Catalog",
        "",
        "Generated from `SKILL.md` frontmatter by `scripts/generate_catalog.py`. Do not edit this file by hand.",
        "",
        f"Total skills: {len(skills)}",
        "",
        "## Categories",
        "",
        *build_category_table(by_category, descriptions, "#"),
    ]

    for category in sorted(by_category):
        lines.extend([
            "",
            f"## {category}",
            "",
            descriptions.get(category, ""),
            "",
            "| Skill | Description |",
            "|---|---|",
        ])
        for skill in by_category[category]:
            rel = skill.path.parent.relative_to(ROOT).as_posix()
            lines.append(markdown_table_row([f"[{skill.name}]({rel}/)", shorten(skill.description)]))

    lines.append("")
    return "\n".join(lines)


def build_readme_table(skills: list[Skill], descriptions: dict[str, str]) -> str:
    by_category = group_by_category(skills)
    lines = [TABLE_START, *build_category_table(by_category, descriptions, "", "/"), TABLE_END]
    return "\n".join(lines)


def update_readme(skills: list[Skill], descriptions: dict[str, str]) -> None:
    table = build_readme_table(skills, descriptions)
    text = README.read_text(encoding="utf-8")

    if TABLE_START not in text or TABLE_END not in text:
        raise ValueError("README is missing generated category table markers")

    pattern = re.compile(rf"{re.escape(TABLE_START)}.*?{re.escape(TABLE_END)}", re.DOTALL)
    updated = pattern.sub(table, text, count=1)
    README.write_text(updated, encoding="utf-8")


def main() -> None:
    descriptions = load_category_descriptions()
    skills = iter_skills()
    CATALOG.write_text(build_catalog(skills, descriptions), encoding="utf-8")
    update_readme(skills, descriptions)
    print(f"Generated {CATALOG.relative_to(ROOT)} and {README.relative_to(ROOT)} with {len(skills)} skills")


if __name__ == "__main__":
    main()
