#!/usr/bin/env python3
"""Generate CATALOG.md from SKILL.md frontmatter."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "CATALOG.md"
SKIP_DIRS = {".git", ".github", "node_modules"}
CATEGORY_DESCRIPTIONS = {
    "ai-tools": "AI agents, MCP integrations, web search, and LLM tooling",
    "app-store": "App Store Connect, ASO, RevenueCat, screenshots, and simulators",
    "coding": "Programming, debugging, testing, code review, and PR workflows",
    "creative": "Writing, editing, media production, video, and content creation",
    "devops": "CI/CD, GitHub workflows, Docker, MLOps, cloud deployment, and infrastructure",
    "external-services": "External service CLIs and API integrations",
    "finance": "Investing, market analysis, portfolio management, earnings, and comps",
    "marketing": "Ads, SEO, analytics, social media, content strategy, and growth",
    "media": "Media content tools",
    "memory": "Memory management, setup, garbage collection, and recall",
    "productivity": "Email, notes, Apple apps, smart home, local search, documents, and gaming",
    "research": "Deep research, competitive analysis, market intelligence, and papers",
    "skills-meta": "Skills about creating, auditing, improving, testing, and cleaning up skills",
    "visual-design": "UI/UX design, diagrams, image generation, frontend design, and design systems",
}


@dataclass(frozen=True)
class Skill:
    category: str
    path: Path
    name: str
    description: str


def first_sentence(text: str, limit: int = 220) -> str:
    text = re.sub(r"\s+", " ", text).strip()
    if len(text) <= limit:
        return text
    cut = text[: limit - 1].rsplit(" ", 1)[0]
    return f"{cut}…"


def parse_frontmatter(path: Path) -> tuple[str, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return path.parent.name, ""

    end = text.find("\n---", 4)
    if end == -1:
        return path.parent.name, ""

    frontmatter = text[4:end].splitlines()
    data: dict[str, str] = {}
    i = 0
    while i < len(frontmatter):
        line = frontmatter[i]
        if not line.strip() or line.lstrip().startswith("#") or ":" not in line:
            i += 1
            continue
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        if value in {"|", ">", "|-", ">-"}:
            block: list[str] = []
            i += 1
            while i < len(frontmatter) and (frontmatter[i].startswith(" ") or not frontmatter[i].strip()):
                block.append(frontmatter[i].strip())
                i += 1
            data[key] = " ".join(block).strip()
            continue
        data[key] = value.strip('"\'')
        i += 1

    return data.get("name") or path.parent.name, data.get("description", "")


def iter_skills() -> list[Skill]:
    skills: list[Skill] = []
    for path in ROOT.glob("**/SKILL.md"):
        rel = path.relative_to(ROOT)
        if any(part in SKIP_DIRS or part.startswith(".") for part in rel.parts):
            continue
        category = rel.parts[0]
        name, description = parse_frontmatter(path)
        skills.append(Skill(category, path, name, description))
    return sorted(skills, key=lambda s: (s.category, str(s.path)))


def markdown_table_row(values: list[str]) -> str:
    escaped = [value.replace("|", "\\|").replace("\n", " ") for value in values]
    return "| " + " | ".join(escaped) + " |"


def build_catalog(skills: list[Skill]) -> str:
    by_category: dict[str, list[Skill]] = {}
    for skill in skills:
        by_category.setdefault(skill.category, []).append(skill)

    lines = [
        "# Skills Catalog",
        "",
        "Generated from `SKILL.md` frontmatter by `scripts/generate_catalog.py`. Do not edit this file by hand.",
        "",
        f"Total skills: {len(skills)}",
        "",
        "## Categories",
        "",
        "| Category | Skills | Description |",
        "|---|---:|---|",
    ]

    for category in sorted(by_category):
        description = CATEGORY_DESCRIPTIONS.get(category, "")
        lines.append(markdown_table_row([f"[{category}](#{category})", str(len(by_category[category])), description]))

    for category in sorted(by_category):
        lines.extend([
            "",
            f"## {category}",
            "",
            f"{CATEGORY_DESCRIPTIONS.get(category, '')}",
            "",
            "| Skill | Description |",
            "|---|---|",
        ])
        for skill in by_category[category]:
            rel = skill.path.parent.relative_to(ROOT).as_posix()
            lines.append(markdown_table_row([f"[{skill.name}]({rel}/)", first_sentence(skill.description)]))

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    skills = iter_skills()
    CATALOG.write_text(build_catalog(skills), encoding="utf-8")
    print(f"Generated {CATALOG.relative_to(ROOT)} with {len(skills)} skills")


if __name__ == "__main__":
    main()
